version: '3.8'
services:
  ingilizce_api:
    build: .
    image: ingilizce-app:latest
    container_name: ingilizce_api_backend
    ports:
      - "8000:5000"
    volumes:
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
    restart: always