
services:
  # Backend API Servisi (Port 8000)
  ingilizce_api:
    build: .
    image: ingilizce-app:latest
    container_name: ingilizce_api_backend
    ports:
      - "8000:5000"
    volumes:
      - .:/app 
    restart: always
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=super-secret-key-2024
    networks:
      - ingilizce_network

  # Frontend Web Servisi (Port 8090)
  ingilizce_frontend:
    image: nginx:alpine
    container_name: ingilizce_web_frontend
    ports:
      - "8090:80"
    volumes:
      - .:/usr/share/nginx/html
    restart: always
    depends_on:
      - ingilizce_api
    networks:
      - ingilizce_network

networks:
  ingilizce_network:
    driver: bridge

